version: "3"

services:
 db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pa55word
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: rootpassword
 